投稿一覧　Posts ExplorerとFollowing Postsのフロント部分
Progate/tweet_app_for_path_intern_D_team pull request #9
Opened 2023-08-23 01:03 UTC by matsuo1234567

# Objective and links

- Objective
- Asana Task URL:https://app.asana.com/0/0/1205301260286640/f

## What was changed

・Posts Explorerの見た目
・Following Postsの見た目
・Posts ExplorerのページにあるBack to Following Posts →をクリックするとFollowing Postsに画面遷移
・Following PostsのページにあるExplore all posts →をクリックするとPosts Explorerに画面遷移

<img width="696" alt="スクリーンショット 2023-08-23 10 01 43" src="https://github.com/Progate/tweet_app_for_path_intern_D_team/assets/122419523/105af467-2813-4abd-8500-e06de8eeb7a0">
<img width="625" alt="スクリーンショット 2023-08-23 10 01 50" src="https://github.com/Progate/tweet_app_for_path_intern_D_team/assets/122419523/5c3da315-a81f-482f-a7bc-b1d762607e8c">

## What was not changed

## Deploy dependencies

## QA

### local

### staging

## Review deadline

## Others

figmaと比べるとExplore all posts →やBack to Following Posts →の位置が少し下になってしまったのですが、これは許容範囲でしょうか？

2023-08-23 12:35 UTC, hapoon requested changes
確認しました。
いくつか不要なファイルがコミットされてたり、必要なファイルが削除されているので修正お願いします。

ちなみにOthersで気にされてた件は、posts-navigationクラスにもCSSを新たに適用することでFollowing PostsとExplore all postsの位置関係をfigma同等にすることは可能です
例えば、`display: flex` と `justify-content: space-between` のように。

2023-08-23 12:35 UTC, hapoon commented on .DS_Store
本ファイルはリモートにプッシュする必要がないので削除しましょう。

2023-08-23 12:35 UTC, hapoon commented on .env.sample
本ファイルのような各人で書き換えるサンプルファイルは削除しないようにしましょう。

2023-08-23 12:35 UTC, hapoon commented on .env.test.sample
本ファイルのような各人で書き換えるサンプルファイルは削除しないようにしましょう。

2023-08-23 12:35 UTC, hapoon commented on src/.DS_Store
本ファイルはリモートにプッシュする必要がないので削除しましょう。

2023-08-23 12:35 UTC, hapoon commented on src/db/.DS_Store
本ファイルはリモートにプッシュする必要がないので削除しましょう。

2023-08-23 12:35 UTC, hapoon commented on src/routes/post.ts
> +postRouter.get("/allposts", ensureAuthUser, async (req, res, next) => {
この対応によって個別のpostが表示できなくなっていますので修正しましょう。
例) posts/7などで `Cannot GET /posts/7` と表示されます

2023-08-23 12:35 UTC, hapoon commented on ts-node
これもチームリポジトリには不要なので削除しましょう。

2023-08-23 12:35 UTC, hapoon commented on tweet_app@1.0.0
これもプッシュは不要です。

2023-08-23 12:35 UTC, hapoon commented on package.json
> +    "nodemon": "^3.0.1",
nodemonを最新にしたのって何か理由あります？

2023-08-28 23:01 UTC, matsuo1234567 commented on package.json
> +    "nodemon": "^3.0.1",
このファイルは何も触っていないです。

2023-08-29 12:55 UTC, hapoon approved these changes
LGTM

2023-08-29 12:55 UTC, hapoon commented on src/routes/post.ts
> +});
👍

2023-08-29 12:55 UTC, merged